#ifndef _CLIENT_API_FX_ACTION_H_
#define _CLIENT_API_FX_ACTION_H_

enum class FXAction {
    HISTORY = 10,
    HISTORY_MINBAR,
    CHECKIN,
    TICK,
    MINBAR,
    NOACTION,
    PLACE_BUY,
    PLACE_SELL,
    INIT_TIME,
    REQUEST_HISTORY_MINBAR,
    PROFIT,
    CLOSE_POS,
    ASK_PAIR,
    PAIR_HIST_X,
    PAIR_HIST_Y,
    PAIR_MIN_OPEN,
    CLOSE_ALL_POS,
    SYM_HIST_OPEN,
    PAIR_POS_PLACED,
    PAIR_POS_CLOSED
};
#endif // _CLIENT_API_FX_ACTION_H_
